### ISSUE TITLE
currentPurchase / 1000 повторяется три раза

### ISSUE THREAD

**Issue by coursar** [Leonid716/SportmasterBonus#7]
https://github.com/Leonid716/SportmasterBonus/blob/e364da1c3ddcd78aa742ee8a10b3eeccadf9b2b8/src/main/java/sportmasterBonus/BonusProgram.java#L7

**Comment by Leonid716** [comment]
https://github.com/Leonid716/SportmasterBonus/commit/702b70c474eab671619f9566d917e96fc668f9a6

**Comment by coursar** [comment]
Когда закрываете таску сообщением коммита, надо в сообщении коммита (то, что вы вводите в окошке PyCharm) писать "fixes #7. Сообщение коммита".
