### ISSUE TITLE
Имеет ли смысл эта строка?

### ISSUE THREAD

**Issue by coursar** [Leonid716/SportmasterBonus#8]
https://github.com/Leonid716/SportmasterBonus/blob/e364da1c3ddcd78aa742ee8a10b3eeccadf9b2b8/src/main/java/sportmasterBonus/BonusProgram.java#L16

**Comment by Leonid716** [comment]
https://github.com/Leonid716/SportmasterBonus/commit/702b70c474eab671619f9566d917e96fc668f9a6
